version: 1.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

platform: Any CPU

configuration: Release

build:
  project: .\Sitecore.React.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: detailed

before_build:
  - nuget restore Sitecore.React.sln

nuget:
  account_feed: true
  project_feed: true

pull_requests:
  do_not_increment_build_number: true

test: off
image: Visual Studio 2017
after_build:
  - ps: .\pack.ps1
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/guitarrich-2gfg89qeypb5
  api_key:
    secure: c/6t8fLGB8rXkTmjwZJmGjAlZwb92rpGN4A3iNOddmc=
  artifact: /.*\.nupkg/
- provider: NuGet
  symbol_server: https://ci.appveyor.com/nuget/sitecore-react-vgd5n8xvyw00/api/v2/package
  api_key:
    secure: 7gjxcs5gkjkq1ltqycvdmipt
  artifact: /.*\.nupkg/
